name: Docker CI - Test on multiple OS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for multi-arch builds)
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run backend tests inside container
        run: docker-compose exec backend sh -c "pytest tests/"

      - name: Tear down containers
        run: docker-compose down

  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (optional for Windows)
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run backend tests inside container
        run: docker-compose exec backend sh -c "pytest tests/"

      - name: Tear down containers
        run: docker-compose down

  test-on-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run backend tests inside container
        run: docker-compose exec backend sh -c "pytest tests/"

      - name: Tear down containers
        run: docker-compose down
